### ISSUE TITLE
Ability to play multiple Chunks sequentially.

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#132]
## User Story
As a translator I would like the ability to playback a selected number of files in order to check the quality of a "Chapter" at a time and listen to the flow of recording.  This would allow a translator to identify necessary cuts and potential retakes when comparing recordings

## Definition of Done
From the file management screen, allow for selection of multiple files to be played sequentially.

**Comment by vleong2332** [comment]
Blocked by at least #177

**Comment by vleong2332** [comment]
The UI is built. Passing this off to @jsarabia1247

**Comment by Redmayspecial** [comment]
Now that Chapters can be complied, scrubbable, and able to be listened to at one time, does that negate the ability to select specific chunks and verses for playback.

**Comment by Redmayspecial** [comment]
Hi Glenn, 
I would agree and I believe the chapter compiling is what resolves this issue.    “Done” in my mind.  

Dan Kramer                                                                                                                          

Director of Education Services                                
Office:  407-852-5357 
Cell: 248-739-2022                        
                   



From: Glenn Oliver 
Sent: Monday, October 3, 2016 2:21 PM
To: Doug White <doug_white@wycliffeassociates.org>; Dan Kramer <dan_kramer@wycliffeassociates.org>
Cc: Joe Sarabia <joe_sarabia@wycliffeassociates.org>
Subject: Would like to remove a User Story...

Doug and Dan,

We currently have a User Story that asks the following…

Ability to play multiple Chunks sequentially.

User Story
As a translator I would like the ability to playback a selected number of files in order to check the quality of a "Chapter" at a time and listen to the flow of recording. This would allow a translator to identify necessary cuts and potential retakes when comparing recordings
This User Story was created BEFORE we had the ability to compile the whole chapter and listen back to it for quality and consistency.  The title specifies CHUNKS, but as I read it, it sounds as though we’ve covered the intent by being able to listen to the Chapter wav.  

Would you agree?  If so, we will call this one done.

As a reminder, we only allow the user to create a chapter wavfile, when they have content for every verse, and not before.

Glenn Oliver
Senior Systems Analyst
T: (407) 852-5371
C: (508) 648-9173
