### ISSUE TITLE
Revise the volume meter to reflect activity based on the zero line

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#158]
## User Story
As a translator I need the volume meter to accurately reflect the microphone levels being heard in order to tell me when I am speaking too softly or too loudly.

## Definition of Done
Realign the colors to key off of the zero line in both directions.

It would be cool if peaks left a marker that faded after (approx) a sec so that I could see where and when a spike happens.

**Comment by vleong2332** [comment]
@Redmayspecial @markalolo @jsarabia1247

Can I discuss this with Sam Peckham? I really feel the recording screen can be made more concise. As of now, we have 2 different indicators that have overlapping purposes and we present them to the user in 2 different ways (bar and wave).

In an effort to present a clean and simple feedback to the user, I extracted these requirements from our previous conversations:

- User needs to know **before** recording whether his voice is too loud or too soft.
- User needs to know **during** recording whether his voice is too loud or too soft
- User needs to know where the sweet spot is (in terms of volume) so he can make appropriate adjustments
- User needs to know whether the app is currently recording or not

Is there any other requirement that I'm missing?
