### ISSUE TITLE
Create Folder on the S3 by Project name and then Device subfolder

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#180]
## User Story
Once connected to the Amazon S3 server, I need to include pertinent information like Language & Source and Device UUID surrounding the files that I am uploading in order to help associated the files later.

## Definition of Done
As we have choice in this matter, we elect to create a Project folder that consists of the language code and the source information.  Subfolders underneath will contain the Device UUID that is contributing audio.  The Device UUID folder will be the bucket for the relevant audio

**Comment by jsarabia1247** [comment]
Project subfolder implementation should be done when a workflow/publishing process is implemented. Until then, files are uploaded under the device UUID folder (project info can be extracted from filenames)
