### ISSUE TITLE
Display file name on the recording screen as labels and value

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#338]
## User Story
As a translator I would like a clearer understanding of the information about the file that I'm currently recording.  

## Definition of Done
The current filename display is confusing.  It should be broken down by field name / value.  TAKE should be present only if user/specified

**Comment by vleong2332** [comment]
Not exactly labels and values, but deconstructing the file name to their individual values. Most of the labels are omitted because they can't be mistaken, like language, book, and project type. Chapter and unit (verse/chunk) is displayed whenever necessary.
