### ISSUE TITLE
The Source Audio progress indicator does not reset when replayed

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#380]
## User Story
As a oral translator, I would like the indicator that tracks the playback progress to correctly reset and track when I replay the file.  Currently it gets stuck at the end of the file.

**Comment by jsarabia1247** [comment]
Issue corrected in v0.8.1

Had to do with the player on complete listener firing before the player actually completes. Now seeking to 0 in the listener to guarantee it being reset.
