### ISSUE TITLE
Chucks are being saved as Chapters folders

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#384]
Audio Source :   Acts in chunks
User :  Margo Hoffman
Observed by:  Glenn Oliver and Joe Sarabia

During the course of recording a chapter in Acts, Margo switched the setting from chunks to verses.  From that point, subsequent verses (Act_01_04) would be saved as Chapters  (Ch  04 was newly created and contained Act_01_04)

**Comment by jsarabia1247** [comment]
Issue may have been resolved in v0.20. Has not yet been reproduced.
