### ISSUE TITLE
When inserting audio, a noticeable lag has been observed

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#392]
## User Story
When inserting audio, the app has been observed to miss part of the recording as though lag occurred during the recording. Also it would appear that there is extra space added before and behind the inserted segment

For example:
Original                        
   "One Two Three ...  Seven Eight Nine"

Inserting at the break  
   " Four Five Six"

Result                         
    "One Two Three...Five Six...Seven Eight Nine

**Comment by jsarabia1247** [comment]
Non-issue, verified by using a constant stream of music to insert into the recording
