### ISSUE TITLE
Inserting into a previously recorded file forced the old file to save as a take of the current name

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#395]
## User Story
When Margo finished recording a file (Book_Chapter-08_01) she when the the file manager to begin checking files from the entire chapter.  She chose a file recorded earlier (Book_Chapter-03_01) and decided to insert audio into that file.  Once done she saved the file.  The resulting file had the name (Book_Chapter-08_02)

**Comment by jsarabia1247** [comment]
Unable to reproduce issue in v0.8.1
