### ISSUE TITLE
Allow the user to SYNC the underlying language.json from the Settings page 

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#425]
## User Story

As a FACILITATOR I need a way to update the available language codes in translationRecorder in order to see newly added languages.
## Definition of Done

Right now this process has to be baked into the APK.  However, we need the users to be able to update the language.json file without waiting for a new build.  If they have internet access, they should be able to trigger a sync process from the Setting page to update this on the fly.

**Comment by jsarabia1247** [comment]
Needs to download languages.json, and then insert any new languages into the database
