### ISSUE TITLE
Giving the app a logo

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#43]

**Comment by zoofries** [comment]
Hey, can I help with this? :D

**Comment by markalolo** [comment]
I think that would be great!

<><><><><><><>
Mark Stedman
(407) 852-5416

Innovation happens because there are people out there doing and trying a lot of different things.
-       Edward Felten

**Comment by vleong2332** [comment]
Launcher icon has been updated.
