### ISSUE TITLE
SPIKE: Create wireframes to represent New Project Wizard workflow for approval

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#441]
## User Story

As a facilitator I need to engage tR's New Project Wizard at the start of each book that is being worked on.  
## Definition of Done

How this is done is currently being debated.  As a result, we need to create wire-frames to represent the various options and present to the product owner for direction

ON APP START ...
- [x] Splash Screen
- [x] Project Wizard

ON MAIN MENU ...
- [x] Project Wizard

tS STYLE PROJECT SCREEN ...
- (remove current main screen)
- Continue Project
- or
- Create Project
- Settings Page

**Comment by vleong2332** [comment]
Screens are uploaded to InvisionApp https://projects.invisionapp.com/d/main#/projects/6976406

**Comment by Redmayspecial** [comment]
@vleong2332 @jsarabia1247 @markalolo 

1. We have now learned that the Project Wizard will only be prompted for on first time use OR when there are no projects listed in the management queue
2. The last project used will be designated as the default project unless changed by the facilitator
3. Hitting the "red button" on the main interface will bring the user to the record screen and assume the settings of the default project
