### ISSUE TITLE
Show the range of verses included in a chunk on the recording screen

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#471]
## User Story

As a translator, I would like to know which verses are included in the chunk that I am about to record to make it easier to anticipate the range of text that I need to focus on in the source material.

When not provided text already broken into chunks, a translator must toggle the "+" and "-" buttons on the interface to understand where the current chunk ends and the next begins.
## Definition of Done

Display the information on the screen so that the user does not have to find this out by trial and error each time.

**Comment by vleong2332** [comment]
@Redmayspecial, does it also need to be shown on the Playback Screen?

**Comment by vleong2332** [comment]
![image](https://cloud.githubusercontent.com/assets/11132446/17599537/9c18b1ac-5fcd-11e6-8197-18d645a9d2d4.png)

![image](https://cloud.githubusercontent.com/assets/11132446/17599544/a03b7a08-5fcd-11e6-9714-7144b13b3522.png)
