### ISSUE TITLE
SPIKE:  Wireframe out how the recording/playback interface will look to handle EDIT and RANKING

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#474]
## User Story
As a translator I would like the recording/playback screen to add the ability to add ranking or checking level information on the screen.  I would also like it to enable me to walk-through and eliminate extraneous takes of the same verse or chunk.  BUT I don't want it to clutter the interface or make the buttons too close together.

## Definition of Done
The solution will likely entail using a colored tabbing system on the gray bar area that will change the interface below to reflect the context of the activities mentioned above.

- Mode 1  - Recording and Editing
- Mode 2  - Ranking, Checking, and Culling

**Comment by vleong2332** [comment]
I believe that this has been accomplished.
