### ISSUE TITLE
SPIKE:  Wireframe a new proposed look for the translationRecorder Home Page

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#475]
## User Story
Dan Kramer confirmed the importance of keeping the Home Screen simple and conspicuous.  Following the discussion with Dan Kramer  it was reasoned that the Home Screen could become even more simple by eliminating the need for the settings button and rolling that into the Facilitator Button.

- Facilitator Button - Takes you to the project management screen and gives you access to the files and settings.
- Translator Button - Takes you to the recording screen, allowing for recording, editing, ranking, and culling

On the translator button should include information about the current default project to add a level of confirmation to the facilitator and the literate translator.

**Comment by Redmayspecial** [comment]
![image](https://cloud.githubusercontent.com/assets/11600863/15358384/291949ca-1cd2-11e6-9e01-36217c0d5b8a.png)

**Comment by vleong2332** [comment]
I believe that this has been accomplished.
