### ISSUE TITLE
Enable the translator/checker to rate a take within a verse

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#514]
## User Story

As a translator/checker I want to be able to indicate (to myself or others) which take within a verse I like so that other oral-only translators can understand my preferences.

A Take can has a range of indicators  to demonstrate which takes are favored and which amongst those takes have priority (no star, 1 star, 2 stars, etc.)

Enable approved Wireframe

**Comment by vleong2332** [comment]
The UI for this is built.

**Comment by vleong2332** [comment]
The rating will be a 3-star based rating. Anything more than 3 seems unnecessary.
