### ISSUE TITLE
Recording another take should reset the unit checking level

### ISSUE THREAD

**Issue by vleong2332** [WycliffeAssociates/translationRecorder#528]
If a user tries to record another take for a verse/chunk while that verse/chunk already has a checking level set, we should warn the user that doing so will reset the checking level for that unit.

Make sure we warn them in:
- [ ] File management (unit card list), when recording a new take.
- [ ] Playback screen, when re-record
- [ ] Playback screen, when inserting
- [ ] Playback screen, when cutting

**Comment by vleong2332** [comment]
For now let's just do a text dialog. If we need the visuals later, we can do it.

@Redmayspecial, any thoughts?

**Comment by jsarabia1247** [comment]
Checking level is now on the Chapter level. Recompiling has the necessary dialogs.
