### ISSUE TITLE
Compile a Chapter Wav

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#531]
As a checker, I would like to be able to compile all of the Units (verses or chunks) together into one wav file in order to perform the verse by verse check. 

Definition of Done:
Should be able to press a "compile to chapter" button that will combine all takes into one chapter wav file

**Comment by vleong2332** [comment]
I'll mock this up.

**Comment by vleong2332** [comment]
See epic #534 for the UI

**Comment by vleong2332** [comment]
I think the UI is ready.
