### ISSUE TITLE
Set Checking Level on the Chapter

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#532]
As a checker, I would like to be able to apply a checking level to a chapter as this is a better representation of a check than the individual takes. Ultimately, the checking level should come after the  verse by verse check.

Definition of Done:
Can set the checking level of the Chapter verse

**Comment by vleong2332** [comment]
I'll mock the UI up

**Comment by vleong2332** [comment]
See epic #534 for the UI

**Comment by vleong2332** [comment]
UI is built.
