### ISSUE TITLE
Check button to designate a takes representation in the chapter

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#533]
As a checker, I want to be able to select which takes will comprise the compiled chapter. I'm okay having the highest rated take selected by default, but would like to be able to supersede this decision with a check button.

Definition of Done:
Allow the selection of one (and only one) take per verse using a check button
Allow highest rated take to be selected in the absence of a take being marked with the check button when compiling the chapter

**Comment by vleong2332** [comment]
I'll mock up the UI

**Comment by vleong2332** [comment]
![image](https://cloud.githubusercontent.com/assets/11132446/17623149/9cd97460-606c-11e6-8f38-3e6930102094.png)

**Comment by vleong2332** [comment]
The UI is built.
