### ISSUE TITLE
Checking Level Applied at the Chapter Level

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#534]

**Comment by vleong2332** [comment]
Empty charter

![image](https://cloud.githubusercontent.com/assets/11132446/17627907/f17f238e-6080-11e6-80e6-1a418ed2e377.png)

Chapter in progress

![image](https://cloud.githubusercontent.com/assets/11132446/17627922/fd7ebe7e-6080-11e6-9e9f-7f26a03d6e80.png)

Chapter has all the unit recorded

![image](https://cloud.githubusercontent.com/assets/11132446/17627931/0e226ece-6081-11e6-8bf9-b081662a6a07.png)

Chapter is compiled

![image](https://cloud.githubusercontent.com/assets/11132446/17627950/1c8110f6-6081-11e6-98ac-a5d4b73296f2.png)

Chapter card is expanded

![image](https://cloud.githubusercontent.com/assets/11132446/17627971/34124140-6081-11e6-871c-8141516837a6.png)

Chapter is played

![image](https://cloud.githubusercontent.com/assets/11132446/17627983/42a7fdc6-6081-11e6-8a39-9247ee36e626.png)

Chapter is checked to check level 1

![image](https://cloud.githubusercontent.com/assets/11132446/17628035/790d7332-6081-11e6-83c6-a06062d355ef.png)

Collapsed chapter card with checking level set

![image](https://cloud.githubusercontent.com/assets/11132446/17628053/934d7a58-6081-11e6-81a5-c616194dd4f3.png)
