### ISSUE TITLE
Mockup how a user would interact to place markers in a chunk

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#545]
To consider
- When using a standard chunk as defined on Door 43, it can be calculated exactly how many new verse markers should be available to place.  Therefore, the list of possible markers should be deliberately exhaustive
- The markers might need to be a color distinctly different from the markers place when cutting.  In the same way that the ribbon interface changes when recording or inserting.
- The markers may need to be movable and visible in the chunk during playback to that the user can refine their position

**Comment by vleong2332** [comment]
Mockups are available here https://invis.io/4Z76O8HA7
