### ISSUE TITLE
When choosing Source Audio from the Setting Screen, the keyboard stays up

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#657]
This puts it in the user's way.  The keyboard should be retracted when the language selection has been made on the setting page

![screenshot_2016-10-03-13-34-16](https://cloud.githubusercontent.com/assets/11600863/19047648/c4b774f0-8970-11e6-8a99-2f69e73933e3.png)

**Comment by jsarabia1247** [comment]
Also incorporating hiding the search menu into this (semi related)
