### ISSUE TITLE
Handle corrupted wav files

### ISSUE THREAD

**Issue by jsarabia1247** [WycliffeAssociates/translationRecorder#664]
If the app is destructively closed during a recording, the wav metadata may not be properly written. In the event that this occurs, the UI should communicate this to the facilitator so that they are aware the file is bad; and options should be provided to attempt to recreate the metadata and insert missing markers.

This means:

UI to represent corrupt metadata
Database field to track bad metadata
Recovery options for the file

**Comment by Redmayspecial** [comment]
1) reports corrupted wavefile message to the user
2) Replaced with the Converter to repair
