### ISSUE TITLE
The details regarding Translators is not displayed in natural language on the info panel

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#667]
## User Story

As a Facilitator I would like to be able to read the translator information clearly when tapping on the info icon in order determine who is actually contributing to the project at a glance.
- Up till recently this line was filled with HTML location information
- It now displays no information

**Comment by jsarabia1247** [comment]
Right now I've taken it out- let's talk more about what contribution means, how to track it, whether it is actually desired, etc
