### ISSUE TITLE
Upgrade the Home Screen to the new design look

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#87]

**Comment by Redmayspecial** [comment]
Vicky Leong
Do these buttons are meant to have the same background color? In other screens one has blue and the other has yellow.

**Comment by Redmayspecial** [comment]
![image](https://cloud.githubusercontent.com/assets/11600863/11563699/44478098-99a3-11e5-98e8-621999f58110.png)

But likely using these colors

![image](https://cloud.githubusercontent.com/assets/11600863/11563744/83cac338-99a3-11e5-85c6-6fad0d03d83b.png)

**Comment by vleong2332** [comment]
Done

**Comment by zoofries** [comment]
oooooh! That's very nice!
